# Generated by Django 5.1.2 on 2024-10-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankLoan',
            fields=[
                ('Bln', models.CharField(max_length=20, primary_key='Bln', serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('Loanamount', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phoneno', models.IntegerField()),
            ],
        ),
    ]
